name: Configuration Provider
type: module
description: Enables provision of configuration by extensions.
# core: 8.x
package: Other
dependencies:
 - config

# Information added by Drupal.org packaging script on 2016-09-16
version: '8.x-1.0-beta4'
core: '8.x'
project: 'config_provider'
datestamp: 1473995040
