content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  webmaster: 3
  administrator: 4
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_node_type:
  restaurant: 'a:1:{s:4:"view";a:1:{i:0;s:13:"authenticated";}}'
langcode: fr
