include_home_segment: 1
home_segment_title: Homer
include_title_segment: 1
language_path_prefix_as_segment: 0
_core:
  default_config_hash: 3jAdehcNx4uO4L0m3G6YlWmkulstfN_jVKigkEtDB6E
include_invalid_paths: 0
excluded_paths: ''
segments_separator: null
title_segment_as_link: 0
title_from_page_when_available: 0
langcode: fr
