<?php
use Drupal\Core\Render\Element;
/**
 * Implements hook_theme().
 */
function annonce_theme($existing, $type, $theme, $path)
{
  $tab =  array(
    'annonce' => array(
      //'template' => 'annonce',
      'render element' => 'elements',
    ),
  );
  return $tab;
}


function template_preprocess_annonce(array &$variables) {
  //$variables['content'] = [];
  $annonce = $variables['elements']['#annonces'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function annonce_theme_suggestions_annonce(array $variables)
{
  $suggestions = array();
  $annonce = $variables['elements']['#annonce'];
  //$sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  
  $suggestions[] = 'annonce__' . $sanitized_view_mode;
  $suggestions[] = 'annonce__' . $annonce->bundle();
  //$suggestions[] = 'annonce__' . $annonce->bundle();
  //$suggestions[] = 'annonce__' . $annonce->id();
  $suggestions[] = 'annonce__' . $annonce->id();
  
  return $suggestions;
  
  
}