name: Configuration Synchronizer
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
# core: 8.x
dependencies:
 - config_provider
 - config_update
configure: config_sync.initialize
# Information added by Drupal.org packaging script on 2016-09-23
version: '8.x-1.0-alpha4'
core: '8.x'
project: 'config_sync'
datestamp: 1474598953
